# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_auto_20181019_1931'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
